---
- hosts: all
  become: true
  tasks:
    - name: Updating OS
      ansible.builtin.apt:
        update_cache: true
        upgrade: yes

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - vim
        - git
        - unzip

    - name: Install Docker requirements
      block:
        - name: Add Key
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add repository
          ansible.builtin.apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu jammy stable
            state: present

    - name: Install Kubectl requirements
      block: 
        - name: add Kubectl GCP key
          ansible.builtin.apt_key:
            url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
            state: present

        - name: Add Kubectl repository
          ansible.builtin.apt_repository:
            repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
            state: present

    - name: Update apt-cache
      ansible.builtin.apt:
        update_cache: true
        state: latest

    - name: Install Docker
      ansible.builtin.apt:
        name: "{{item}}"
        state: latest
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Add the user 'joao' to group 'docker'
      ansible.builtin.user:
        name: joao
        groups: docker
        append: yes

    - name: Install Kubectl
      apt:
        name: kubectl
        state: present

    - name: Install AWS
      block:
        - name: Unarchive a file that needs to be downloaded (added in 2.0)
          ansible.builtin.unarchive:
            src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
            dest: ./
            remote_src: yes

        - name:
          ansible.builtin.command: sudo ./aws/install

        - name:
          ansible.builtin.command: sudo rm -rf ./aws

  handlers:
    - name: Restart docker
      service:
        name: docker
        state: restarted