---
- hosts: all
  become: true
  tasks:
    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: latest

    - name: Update apt-cache
      ansible.builtin.apt:
        update_cache: true
        upgrade: yes

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - curl
        - ca-certificates
        - apt-transport-https
        - gnupg
        - unzip

    - name: Install Java
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Docker requirements
      block:
        - name: Add Key
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add repository
          ansible.builtin.apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu jammy stable
            state: present

    - name: Install Kubectl requirements
      block: 
        - name: add Kubectl GCP key
          ansible.builtin.apt_key:
            url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
            state: present

        - name: Add Kubectl repository
          ansible.builtin.apt_repository:
            repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
            state: present

    - name: Install Jenkins requirements
      block: 
        - name: Install Jenkins key
          ansible.builtin.apt_key:
            url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
            state: present

        - name: Checking Jenkins repository
          ansible.builtin.apt_repository:
            repo: deb https://pkg.jenkins.io/debian-stable binary/
            state: present

    - name: Update apt-cache
      ansible.builtin.apt:
        update_cache: true
        state: latest

    - name: install docker
      ansible.builtin.apt:
        name: "{{item}}"
        state: latest
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Add the user 'ubuntu' to group 'docker'
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Kubectl
      apt: 
        name: kubectl
        state: present

    - name: Install Jenkins
      apt: 
        name: jenkins
        state: latest

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted

    - name: Start Jenkins
      service:
        name: jenkins
        enabled: true
        state: started